### ISSUE TITLE
Cant Open the image and Play the video

### ISSUE THREAD

**Issue by RagulAnand** [relatedcode/NotificationChat#112]

**Comment by RagulAnand** [comment]
But I solved it by slightly changing the code. Now its working good

**Comment by cohe4ko** [comment]
Hello.
Can you give me the changes?

**Comment by RagulAnand** [comment]
Use this below code at didTapMessageBubbleAtIndexPath in ChatView.m


 JSQMessage *message = messages[indexPath.item];
    if (message.isMediaMessage)
    {
        NSString *imgOrvdo=[NSString stringWithFormat:@"%@",message.media];
        if ([imgOrvdo containsString:@"JSQPhotoMediaItem"]) {
            PhotoMediaItem *mediaItem = (PhotoMediaItem *)message.media;
            NSArray *photos = [IDMPhoto photosWithImages:@[mediaItem.image]];
            IDMPhotoBrowser *browser = [[IDMPhotoBrowser alloc] initWithPhotos:photos];
            [self presentViewController:browser animated:YES completion:nil];
        }
        else if ([imgOrvdo containsString:@"JSQVideoMediaItem"])
        {
            VideoMediaItem *mediaItem = (VideoMediaItem *)message.media;
            MPMoviePlayerViewController *moviePlayer = [[MPMoviePlayerViewController alloc] initWithContentURL:mediaItem.fileURL];
            [self presentMoviePlayerViewControllerAnimated:moviePlayer];
            [moviePlayer.moviePlayer play];
        }
    }
