### ISSUE TITLE
Push Notification deep linking should be implemented

### ISSUE THREAD

**Issue by relatedcode** [relatedcode/NotificationChat#96]

**Comment by groschovskiy** [comment]
void SendPushNotification(NSString *groupId, NSString *text)
{
	PFQuery *query = [PFQuery queryWithClassName:PF_MESSAGES_CLASS_NAME];
	[query whereKey:PF_MESSAGES_GROUPID equalTo:groupId];
	[query whereKey:PF_MESSAGES_USER notEqualTo:[PFUser currentUser]];
	[query includeKey:PF_MESSAGES_USER];
	[query setLimit:250];

	PFQuery *queryInstallation = [PFInstallation query];
	[queryInstallation whereKey:PF_INSTALLATION_USER matchesKey:PF_MESSAGES_USER inQuery:query];

    NSDictionary *data = @{
                           @"alert": text,
                           @"badge": @"Increment",
                           @"sound": @"chime"
                           };
    
    PFPush *push = [[PFPush alloc] init];
    [push setQuery:queryInstallation];
    [push setData:data];
    [push sendPushInBackgroundWithBlock:^(BOOL succeeded, NSError *error)
     {
         if (error != nil)
         {
             NSLog(@"SendPushNotification send error.");
         }
     }];
}
