### ISSUE TITLE
Push Notifications Should Be Sent Using Cloud Code

### ISSUE THREAD

**Issue by StormFactory** [relatedcode/NotificationChat#99]
@relatedcode I think this would be a better and more secure way of sending Push Notifications instead of through the client.  If you don't want to switch to this Cloud Code method and you haven't added this because it would complicate the project for people downloading, let me know.

**Comment by relatedcode** [comment]
@StormFactory I do know that push notification should be sent from Cloud Code. But this is only a sample/educational code. I think this will be as it is now. Thanks anyway.

**Comment by StormFactory** [comment]
@relatedcode Check out this post from Parse regarding the topic. http://blog.parse.com/2014/09/03/the-dangerous-world-of-client-push/

I understand that it's sample/education code and that it needs more to be in production, but just in case people try to use the as is, I'm thinking that maybe they should be aware of the above.

**Comment by relatedcode** [comment]
@StormFactory Thanks. I do know this article.
